<?php

$advancedPlan = false;
$class = 'disabledDiv';
$disableInput = 'disabled="disabled"';
if ($this->currentPlan == 3) {
    $advancedPlan = true;
    $class = '';
    $disableInput = '';
}
?>
<script type="text/javascript">
    var unishippersSmDsAjaxUrl = '<?= /* @noEscape */ $block->getDsAjaxUrl() ?>';
</script>
</form> <!-- Needed to close Admin Config Form -->

<div class="main-container">
    <h1>
        <?= /* @noEscape */ __('Drop Ships') ?>
    </h1>

    <a href="#add-ds-btn" class="en-btn" id="unishipperssm-add-ds-btn" title="<?= __('Add Drop Ship') ?>">
        <?= $block->escapeHtmlAttr('Add') ?>
    </a>
    <div class="wh-text ds">
        <p>
            <?= /* @noEscape */ __("Locations that inventory specific items that are drop shipped to the destination. Use the product's settings page to identify it as a drop shipped item and its associated drop ship location. Orders that include drop shipped items will display a single figure for the shipping rate estimate that is equal to the sum of the cheapest option of each shipment required to fulfill the order.") ?>
        </p>
    </div>

    <div class="message message-success success unishipperssm-ds-msg"></div>

    <table class="warehouse" id="append-dropship">
        <thead>
        <tr>
            <th>
                <?= $block->escapeHtmlAttr(__('Nickname')) ?>
            </th>
            <th>
                <?= /* @noEscape */ __('City') ?>
            </th>
            <th>
                <?= /* @noEscape */ __('State') ?>
            </th>
            <th>
                <?= /* @noEscape */ __('Zip') ?>
            </th>
            <th>
                <?= /* @noEscape */ __('Country') ?>
            </th>
            <th>
                <?= /* @noEscape */ __('Action') ?>
            </th>
        </tr>
        </thead>
        <tbody>
        <?php

        if ($block->dropships) {
            foreach ($block->dropships as $r) { ?>
                <tr id="row_<?= /* @noEscape */ $r['warehouse_id']; ?>" data-id="<?= /* @noEscape */ $r['warehouse_id']; ?>">
                    <td>
                        <?= /* @noEscape */ $r['nickname']; ?>
                    </td>
                    <td>
                        <?= /* @noEscape */ $r['city']; ?>
                    </td>
                    <td>
                        <?= /* @noEscape */ $r['state']; ?>
                    </td>
                    <td>
                        <?= /* @noEscape */ $r['zip']; ?>
                    </td>
                    <td>
                        <?= /* @noEscape */ $r['country']; ?>
                    </td>
                    <td>
                        <a href="javascript:;" data-id="<?= /* @noEscape */ $r['warehouse_id']; ?>" title="<?= /* @noEscape */ __('Edit') ?>" class="unishipperssm-edit-ds">
                            <?= /* @noEscape */ __('Edit') ?>
                        </a> |
                        <a href="javascript:;" data-id="<?= /* @noEscape */ $r['warehouse_id']; ?>" title="<?= /* @noEscape */ __('Delete') ?>" class="unishipperssm-del-ds">
                            <?= /* @noEscape */ __('Delete') ?>
                        </a>
                    </td>
                </tr>
                <?php
            }
        } ?>
        </tbody>
    </table>
</div>
<!-- Add Popup for new dropship -->
<div id="unishipperssm-ds-modal" class="add-wh-popup">

    <form method="post" id="unishipperssm-ds-form" enctype="multipart/form-data" autocomplete="off" data-mage-init='{"validation":{}}' >

        <div class="message message-error error unishipperssm-ds-er-msg""></div>
        <input type="hidden" name="location" value="dropship">
        <input type="hidden" name="dropshipId" id="ds-edit-form-id">

        <div class="add-wh-input">
            <div class="wh-input-label">
                <?= /* @noEscape */ __('Nickname') ?>
            </div>
            <div class="wh-input">
                <input type="text" class="input-text" title="<?= __('Nickname') ?>" value="" name="nickname" placeholder="Nickname" id="unishipperssm-ds-nickname">
            </div>
        </div>

        <div class="add-wh-input">
            <div class="wh-input-label add-asterisk">
                <?= /* @noEscape */ __('Zip') ?>
            </div>
            <div class="wh-input">
                <input type="text" class="required validate-alphanum" title="<?= /* @noEscape */ __('Zip') ?>" maxlength="6" name="zip" placeholder="30214" id="unishipperssm-ds-zip">
            </div>
        </div>

        <div class="add-wh-input city-input">
            <div class="wh-input-label add-asterisk">
                <?= /* @noEscape */ __('City') ?>
            </div>
            <div class="wh-input">
                <input class="required" type="text" title="<?= /* @noEscape */ __('City') ?>" name="city" placeholder="Fayetteville" id="ds-city">
            </div>
        </div>

        <div class="add-wh-input city-select" style="display:none;">
            <div class="wh-input-label add-asterisk">
                <?= /* @noEscape */ __('City') ?>
            </div>
            <div class="wh-input">
                <select id="ds-actname" value=""></select>
            </div>
        </div>

        <div class="add-wh-input">
            <div class="wh-input-label add-asterisk">
                <?= /* @noEscape */ __('State') ?>
            </div>
            <div class="wh-input">
                <input type="text" class="required validate-alpha" title=<?= /* @noEscape */ __('State') ?> maxlength="2" class="alphaonly" name="state" placeholder="GA" id="ds-state">
            </div>
        </div>

        <div class="add-wh-input">
            <div class="wh-input-label add-asterisk">
                <?= /* @noEscape */ __('Country') ?>
            </div>
            <div class="wh-input">
                <input type="text" class="required validate-alpha" title=<?= /* @noEscape */ __('Country') ?> maxlength="2" name="country" placeholder="US" id="ds-country">
            </div>
        </div>

        <!--In store Pickup Section-->
        <h2 class="wh-heading is-heading-left" id="ds-is-heading-left">
            <?= /* @noEscape */ __('In-store Pick Up') ?>
        </h2>

        <?php if (!$advancedPlan): ?>
            <a class="is-heading-right" href="https://eniture.com/magento2-ups-ltl-freight">
                <?= /* @noEscape */ __('Advanced Plan Required') ?>
            </a>
        <?php endif; ?>

        <div class="message message-error error ds-instore-miles-postal-err">
            <?= /* @noEscape */ __('You must provide Miles or Postal Code.') ?>
        </div>

        <div id="disableddiv" class="<?= /* @noEscape */ $class ?>">
            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= /* @noEscape */ __('Enable In-Store Pick Up') ?>
                </div>
                <div class="wh-input">
                    <input type="checkbox" title="<?= /* @noEscape */ __('Enable In-Store Pick Up') ?>" name="instore-enable" id="ds-enable-instore-pickup" <?= /* @noEscape */ $disableInput ?>>
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= /* @noEscape */ __('Offer if address is within (miles):') ?>
                </div>
                <div class="wh-input">
                    <input type="text" title="<?= /* @noEscape */ __('Offer if address is within (miles)') ?>" class="digits" maxlength="3" name="is-within-miles" id="ds-within-miles" <?= /* @noEscape */ $disableInput ?> onpaste="return false">
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= /* @noEscape */ __('Offer if postal code matches:') ?>
                </div>
                <div class="wh-input">
                    <input type="text" title="<?= /* @noEscape */ __('Offer is postal code matches') ?>"  data-role="<?= /* @noEscape */ $advancedPlan? 'tagsinput': ''; ?>" name="is-postcode-match" id="ds-postcode-match" <?= /* @noEscape */ $disableInput ?>>
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= /* @noEscape */ __('Check Out Description:') ?>
                </div>
                <div class="wh-input">
                    <input type="text" title="<?= /* @noEscape */ __('Check Out Description') ?>" maxlength="25" name="is-checkout-descp"  placeholder="In-store pick up" id="ds-checkout-descp" <?= /* @noEscape */ $disableInput ?>>
                </div>
            </div>
        </div>
        <!--In store Pickup Section End-->

        <!--Local Delivery Section-->

        <div class="row" style="clear: both">
            <h2 class="wh-heading ld-heading-left" id="ds-ld-heading-left">
                <?= /* @noEscape */ __('Local Delivery') ?>
            </h2>
            <?php if (!$advancedPlan): ?>
                <a class="ld-heading-right" href="https://eniture.com/magento2-ups-ltl-freight/">
                    <?= /* @noEscape */ __('Advanced Plan Required') ?>
                </a>
            <?php endif;?>
        </div>

        <div class="message message-error error ds-local-miles-postals-err">
            <?= /* @noEscape */ __('You must provide Miles or Postal Code.') ?>
        </div>

        <div id="disableddiv" class="<?= /* @noEscape */ $class ?>">

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= /* @noEscape */ __('Enable Local Delivery') ?>
                </div>
                <div class="wh-input">
                    <input type="checkbox" title="<?= /* @noEscape */ __('Enable Local Delivery') ?>" name="ld-enable" id="ds-enable-local-delivery" <?= /* @noEscape */ $disableInput ?>>
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= /* @noEscape */ __('Offer if address is within (miles):') ?>
                </div>
                <div class="wh-input">
                    <input type="text" title="<?= /* @noEscape */ __('Offer if address is within (miles)') ?>" class="digits" maxlength="3" name="ld-within-miles" id="ds-ld-within-miles" <?= /* @noEscape */ $disableInput ?> onpaste="return false">
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= /* @noEscape */ __('Offer if postal code matches:') ?>
                </div>
                <div class="wh-input">
                    <input type="text" title="<?= /* @noEscape */ __('Offer is postal code matches') ?>" data-role="<?= /* @noEscape */ $advancedPlan? 'tagsinput': ''; ?>" name="ld-postcode-match"  id="ds-ld-postcode-match" <?= /* @noEscape */ $disableInput ?>>
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= /* @noEscape */ __('Check Out Description:') ?>
                </div>
                <div class="wh-input">
                    <input type="text" title="<?= /* @noEscape */ __('Check Out Description') ?>" maxlength="25" name="ld-checkout-descp"  placeholder="Local delivery" id="ds-ld-checkout-descp" <?= /* @noEscape */ $disableInput ?>>
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= /* @noEscape */ __('Local Delivery Fee') ?>
                </div>
                <div class="wh-input">
                    <input type="text" title="<?= /* @noEscape */ __('Local Delivery Fee') ?>" class="number validate-unishipperssm-positive-decimal-limit-2" maxlength="5" name="ld-fee" id="ds-ld-fee" <?= /* @noEscape */ $disableInput ?> onpaste="return false">
                </div>
            </div>

            <div class="add-wh-input">
                <div class="wh-input-label">
                    <?= /* @noEscape */ __('Suppress other rates') ?>
                    <div class="suppressTooltip">[ ? ]
                        <span class="suppressTooltiptext"><?= /* @noEscape */ __("This setting only suppresses rates that would otherwise be returned by the Eniture Technology products.") ?></span>
                    </div>
                </div>
                <div class="wh-input">
                    <input type="checkbox" title="<?= /* @noEscape */ __('Suppress other rates') ?>" class="enable-checkbox" name="ld-sup-rates" id="ds-ld-sup-rates" <?= /* @noEscape */ $disableInput ?>>
                </div>
            </div>
        </div>
        <!--Local Delivery Section End-->
        </form>
</div>
