<script type="text/javascript">
    require([ 'jquery', 'jquery/ui'], function($){
        $(document).ready(function($) {
            var carrierdiv = '#UnishippersSmQuoteSetting_third-head';
            unishippersSmCurrentPlanNote($, '<?php echo $this->unishippersSmallPlanNotice(); ?>', carrierdiv);
            unishippersSmPlanQuoteRestriction('<?php echo $this->planRstrctnQuoteSettng(); ?>');
        });
    });
</script>
<?php

if ($block->enable == 'yes') {
    $block->setTemplate('Eniture_ResidentialAddressDetection::/system/config/residentialaddressdetection.phtml');
    echo $block->getHtml();
} else {
    ?>
    <div class="rad">
        <p>
            <?=
            /* @noEscape */ __(
                'Click <a href="%1" target="_blank">here</a> to add the Auto detect residential addresses module.(<a href="%2" target="_blank">Learn more</a>)',
                "https://eniture.com/magento2-residential-address-detection/",
                "https://eniture.com/magento2-residential-address-detection/#documentation"
            )
            ?>
            </p>
        </div>
    <?php
}
