<?php
$advancedPlan = false;
$class = 'disabledDiv';
$disableInput = 'disabled="disabled"';
if ($block->currentPlan == 3) {
    $advancedPlan = true;
    $class = '';
    $disableInput = '';
}
?>
<script>
    require(['jquery', 'domReady!'], function($){
        let carrierDiv = '#UnishippersSmWarehouse_second-head';
        unishippersSmCurrentPlanNote($, '<?php /* @noEscape */ echo $block->unishippersSmallSetPlanNotice(); ?>', carrierDiv);

        let canAddWh = <?php /* @noEscape */ echo $block->canAddWarehouse; ?>;
        unishippersSmAddWarehouseRestriction(canAddWh);
    });
    let unishippersSmAjaxUrl = '<?= /* @noEscape */ $block->getAjaxUrl() ?>';
    let unishippersSmAdvancePlan = '<?= /* @noEscape */ $advancedPlan ?>';

</script>
</form>
<div class="main-container">
    <h1>
        <?= /* @noEscape */
         __('Warehouses')
        ?>
    </h1>
    <a href="#" class="en-btn" id="unishipperssm-add-wh-btn" title="<?= /* @noEscape */ __('Add Warehouse') ?>">
        <?= /* @noEscape */ __('Add') ?>
    </a>
    <div class="wh-text">
        <p>
            <?= /* @noEscape */
             __('Warehouses that inventory all products not otherwise identified as drop shipped items. The warehouse with the lowest shipping cost to the destination is used for quoting purposes.')
            ?>
        </p>
    </div>
    <div class="message message-success success unishipperssm-wh-msg"></div>

    <table class="warehouse" id="append-warehouse">
        <thead>
        <tr>
            <th>
                <?=
                /* @noEscape */ __('City')
                ?>
            </th>
            <th>
                <?=
                /* @noEscape */ __('State')
                ?>
            </th>
            <th>
                <?=
                /* @noEscape */ __('Zip')
                ?>
            </th>
            <th>
                <?=
                /* @noEscape */ __('Country')
                ?>
            </th>
            <th>
                <?=
                /* @noEscape */ __('Action')
                ?>
            </th>
        </tr>
        </thead>
        <tbody>
        <?php
        if ($block->warehouses) {
            foreach ($block->warehouses as $r) {
                ?>
                <tr id="row_<?= /* @noEscape */ $r['warehouse_id']; ?>" data-id="<?= /* @noEscape */ $r['warehouse_id']; ?>">
                    <td>
                        <?= /* @noEscape */ $r['city']; ?>
                    </td>
                    <td>
                        <?= /* @noEscape */ $r['state']; ?>
                    </td>
                    <td>
                        <?= /* @noEscape */ $r['zip']; ?>
                    </td>
                    <td>
                        <?= /* @noEscape */ $r['country']; ?>
                    </td>
                    <td>
                  <a href="javascript:;" data-id="<?= /* @noEscape */ $r['warehouse_id']; ?>" title="<?= /* @noEscape */ __('Edit') ?>" class="unishipperssm-edit-wh">
                        <?= /* @noEscape */  __('Edit') ?>
                  </a> |
                  <a href="javascript:;" data-id="<?= /* @noEscape */ $r['warehouse_id']; ?>" title="<?= /* @noEscape */ __('Delete') ?>" class="unishipperssm-del-wh">
                        <?= /* @noEscape */  __('Delete') ?>
                        </a>
                    </td>
                </tr>
            <?php   }
        }
        ?>
        </tbody>
    </table>

    <hr class="wh-hr">
</div>
<!-- Add Popup for new warehouse -->
<div id="unishipperssm-wh-modal" class="add-wh-popup">
<form method="post" id="unishipperssm-wh-form" enctype="multipart/form-data" autocomplete="off" data-mage-init='{"validation":{}}' >


                <div class="message message-error error unishipperssm-wh-er-msg"></div>
                <input type="hidden" name="location" value="warehouse">
                <input type="hidden" name="originId" id="edit-form-id">
                <div class="add-wh-input">
                    <div class="wh-input-label add-asterisk">
                        <?= /* @noEscape */ __('Zip') ?>
                    </div>
                    <div class="wh-input">
                        <input type="text" class="required-entry validate-alphanum" title="<?= /* @noEscape */ __('Zip') ?>" maxlength="6" name="zip" placeholder="30214" id="unishipperssm-wh-zip">
                    </div>
                </div>

                <div class="add-wh-input city-input">
                    <div class="wh-input-label add-asterisk">
                        <?= /* @noEscape */ __('City') ?>
                    </div>
                    <div class="wh-input">
                        <input type="text" class="required" title="<?= /* @noEscape */ __('City') ?>" name="city" placeholder="Fayetteville" id="wh-origin-city">
                    </div>
                </div>

                <div class="add-wh-input city-select" style="display:none;">
                        <div class="wh-input-label add-asterisk">
                        <?= /* @noEscape */ __('City') ?>
                        </div>
                        <div class="wh-input">
                            <select id="actname"></select>
                        </div>
                </div>

                <div class="add-wh-input">
                        <div class="wh-input-label add-asterisk">
                        <?= /* @noEscape */ __('State') ?>
                        </div>
                    <div class="wh-input">
                    <input type="text" class="required validate-alpha" title="<?= /* @noEscape */ __('State') ?>" maxlength="2" name="state" placeholder="GA" id="wh-origin-state">
                    </div>
                </div>

                <div class="add-wh-input">
                        <div class="wh-input-label add-asterisk">
                        <?= /* @noEscape */ __('Country') ?>
                        </div>
                        <div class="wh-input">
                            <input type="text" class="required  validate-alpha" title="<?= /* @noEscape */ __('Country') ?>" maxlength="2" name="country" placeholder="US" id="wh-origin-country">
                        </div>
                </div>

                <!--In store Pickup Section-->

                    <h3 class="wh-heading is-heading-left" id="wh-is-heading-left">
                        <?=
                        /* @noEscape */ __('In-store Pick Up')
                        ?>
                    </h3>
                    <?php if (!$advancedPlan): ?>
                        <a class="is-heading-right" href="https://eniture.com/magento2-unishippers-small-package/">
                            <?=
                            /* @noEscape */ __('Advanced Plan Required')
                            ?>
                        </a>
                    <?php endif; ?>
                <div class="message message-error error wh-instore-miles-postal-err">
                        <?=
                            /* @noEscape */ __('You must provide Miles or Postal Code.')
                        ?>
                </div>

                <div id="disableddiv" class="<?= /* @noEscape */ $class ?>">
                    <div class="add-wh-input">
                            <div class="wh-input-label">
                            <?= /* @noEscape */ __('Enable In-Store Pick Up') ?>
                            </div>
                            <div class="wh-input">
                            <input type="checkbox" title="<?= /* @noEscape */ __('Enable In-Store Pick Up') ?>" name="instore-enable" id="enable-instore-pickup" <?= /* @noEscape */ $disableInput ?>>
                            </div>
                    </div>

                    <div class="add-wh-input">
                            <div class="wh-input-label">
                            <?= /* @noEscape */ __('Offer if address is within (miles):') ?>
                            </div>
                            <div class="wh-input">
                            <input type="text" title="<?= /* @noEscape */ __('Offer if address is within (miles)') ?>" class="digits" maxlength="3" name="is-within-miles"  id="within-miles" <?= /* @noEscape */ $disableInput ?> onpaste="return false">
                            </div>
                    </div>

                    <div class="add-wh-input">
                            <div class="wh-input-label">
                            <?= /* @noEscape */ __('Offer if postal code matches:') ?>
                            </div>
                            <div class="wh-input">
                            <input type="text" title="<?= /* @noEscape */ __('Offer is postal code matches') ?>"  name="is-postcode-match"  id="postcode-match" data-role="<?= /* @noEscape */ $advancedPlan? 'tagsinput': ''; ?>" <?= /* @noEscape */ $disableInput ?> >
                            </div>
                    </div>

                    <div class="add-wh-input">
                            <div class="wh-input-label">
                            <?= /* @noEscape */ __('Check Out Description:') ?>
                            </div>
                            <div class="wh-input">
                            <input type="text" title="<?= /* @noEscape */ __('Check Out Description') ?>" maxlength="25" name="is-checkout-descp" placeholder="In-store pick up" id="checkout-descp" <?= /* @noEscape */ $disableInput ?>>
                            </div>
                    </div>
                </div>
                <!--In store Pickup Section End-->

                <!--Local Delivery Section-->

                <div class="row" style="clear: both">
                    <h3 class="wh-heading ld-heading-left" id="wh-ld-heading-left" >
                        <?= /* @noEscape */ __('Local Delivery') ?>
                    </h3>
                    <?php if (!$advancedPlan): ?>
                        <a class="ld-heading-right" href="https://eniture.com/magento2-unishippers-small-package/">
                            <?=
                            /* @noEscape */ __('Advanced Plan Required')
                            ?>
                        </a>
                    <?php endif;?>
                </div>
                <div class="message message-error error wh-local-miles-postals-err">
                        <?= /* @noEscape */ __('You must provide Miles or Postal Code.') ?>
                    </div>

                <!--Local Delivery Section Start-->
                <div id="disableddiv" class="<?= /* @noEscape */ $class ?>">

                    <div class="add-wh-input">
                            <div class="wh-input-label">
                            <?= /* @noEscape */ __('Enable Local Delivery') ?>
                            </div>
                            <div class="wh-input">
                            <input type="checkbox" title="<?= /* @noEscape */ __('Enable Local Delivery') ?>" name="ld-enable" id="enable-local-delivery" <?= /* @noEscape */ $disableInput ?>>
                            </div>
                    </div>

                    <div class="add-wh-input">
                            <div class="wh-input-label">
                            <?= /* @noEscape */ __('Offer if address is within (miles):') ?>
                            </div>
                            <div class="wh-input">
                            <input type="text" title="<?= /* @noEscape */ __('Offer if address is within (miles)') ?>" class="digits" maxlength="3" name="ld-within-miles" value=""  id="ld-within-miles" <?= /* @noEscape */ $disableInput ?> onpaste="return false">
                            </div>
                    </div>

                    <div class="add-wh-input">
                            <div class="wh-input-label">
                            <?= /* @noEscape */ __('Offer if postal code matches:') ?>
                            </div>
                            <div class="wh-input">
                            <input type="text" title="<?= /* @noEscape */ __('Offer is postal code matches') ?>" data-role="<?= /* @noEscape */ $advancedPlan? 'tagsinput': ''; ?>" name="ld-postcode-match"  id="ld-postcode-match" <?= /* @noEscape */ $disableInput ?>>
                            </div>
                    </div>

                    <div class="add-wh-input">
                            <div class="wh-input-label">
                            <?= /* @noEscape */ __('Check Out Description:') ?>
                            </div>
                            <div class="wh-input">
                            <input type="text" title="<?= /* @noEscape */ __('Check Out Description') ?>" maxlength="25" name="ld-checkout-descp" placeholder="Local delivery" id="ld-checkout-descp" <?= /* @noEscape */ $disableInput ?>>
                            </div>
                    </div>

                    <div class="add-wh-input">
                            <div class="wh-input-label">
                            <?= /* @noEscape */ __('Local Delivery Fee') ?>
                            </div>
                            <div class="wh-input">
                            <input type="text" title="<?= /* @noEscape */ __('Local Delivery Fee') ?>" class="number validate-unishipperssm-positive-decimal-limit-2" maxlength="5" name="ld-fee"  id="ld-fee" <?= /* @noEscape */ $disableInput ?> onpaste="return false">
                            </div>
                    </div>

                    <div class="add-wh-input">
                            <div class="wh-input-label">
                            <?= /* @noEscape */ __('Suppress other rates') ?>
                        <div class="suppressTooltip">[ ? ]
                                <span class="suppressTooltiptext"><?= /* @noEscape */ __("This setting only suppresses rates that would otherwise be returned by the Eniture Technology products.") ?></span>
                        </div>
                            </div>
                            <div class="wh-input">
                            <input type="checkbox" title="<?= /* @noEscape */ __('Suppress other rates') ?>" name="ld-sup-rates" id="ld-sup-rates" <?= /* @noEscape */ $disableInput ?>>
                            </div>
                    </div>
                </div>
                <!--Local Delivery Section End-->
    </form>
</div>
